export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

export const SET_GENRES = "SET_GENRE";
export const VERIFY_GENRES = "VERIFY_GENRES";

export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";

export const ADD_GENRES_TO_STATE = "ADD_GENRES_TO_STATE";
export const REMOVE_GENRES_FROM_PROFILE = "REMOVE_GENRES_FROM_PROFILE";

export const ADD_MOVIES_TO_STATE = "ADD_MOVIES_TO_STATE";
export const ADD_POSTER_CONFIG_TO_STORES = "ADD_POSTER_CONFIG_TO_STORES";
export const ADD_POSTERS_URL_TO_STORE = "ADD_POSTERS_URL_TO_STORE";

export const INIT_NEW_CHECKBOX = "INIT_NEW_CHECKBOX";
export const TOGGLE_CHECKBOX_TO_FALSE = "TOGGLE_CHECKBOX_TO_FALSE";
export const TOGGLE_CHECKBOX_TO_TRUE = "TOGGLE_CHECKBOX_TO_TRUE";
